language: cpp
compiler: g++

env:
  - CUDA_HOME=/usr/local/cuda PATH=/usr/local/cuda/bin:${PATH}

jobs:
  include:
    # - name: "Ubuntu 14 local hts"
    #   os: linux
    #   dist: trusty
    #   addons:
    #     apt:
    #       packages:
    #         - libhdf5-dev
    #   script: autoreconf && ./scripts/install-hts.sh && ./configure && make && make test
    # - name: "Ubuntu 16 install scripts"
    #   dist: xenial
    #   os: linux
    #   addons:
    #     apt:
    #       packages:
    #         - valgrind
    #   script:
    #     - autoreconf && ./scripts/install-hdf5.sh 2> /dev/null &&./scripts/install-hts.sh && ./configure --enable-localhdf5 && make && make test
    #     - valgrind --leak-check=full --error-exitcode=1 ./f5c call-methylation -b test/ecoli_2kb_region/reads.sorted.bam -g test/ecoli_2kb_region/draft.fa -r test/ecoli_2kb_region/reads.fasta -t 8 -K 256 -B 2M > /dev/null
    # - name: "Ubuntu 16 pure make"
    #   os: linux
    #   dist: xenial
    #   script: make && make test
    # - name: "OSX local hts"
    #   os: osx
    #   addons:
    #     homebrew:
    #       packages:
    #         - hdf5
    #       update: false
    #   script: autoreconf && ./scripts/install-hts.sh && ./configure && make && make test
    # - name: "OSX pure make"
    #   os: osx
    #   script: make && make test
    # - name: "Ubuntu 14 cuda 7.0"
    #   os: linux
    #   dist: trusty
    #   addons:
    #     apt:
    #       packages:
    #         - libhdf5-dev
    #   before_script:
    #     - wget http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1404/x86_64/cuda-repo-ubuntu1404_7.0-28_amd64.deb
    #     - sudo dpkg -i cuda-repo-ubuntu1404_7.0-28_amd64.deb
    #     - sudo apt-get update -qq
    #     - sudo apt-get install -y cuda-drivers cuda-core-7-0 cuda-cudart-dev-7-0
    #     - sudo apt-get clean
    #     - sudo ln -s /usr/local/cuda-7.0/ ${CUDA_HOME}
    #   script: autoreconf && ./scripts/install-hts.sh && ./configure && make cuda=1
    # - name: "Ubuntu 14 cuda 6.5"
    #   os: linux
    #   dist: trusty
    #   before_script:
    #     - wget http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1404/x86_64/cuda-repo-ubuntu1404_7.0-28_amd64.deb
    #     - sudo dpkg -i cuda-repo-ubuntu1404_7.0-28_amd64.deb
    #     - sudo apt-get update -qq
    #     - sudo apt-get install -y cuda-drivers cuda-core-6-5 cuda-cudart-dev-6-5
    #     - sudo apt-get clean
    #     - sudo ln -s /usr/local/cuda-6.5/ ${CUDA_HOME}
    #   script: make cuda=1
    - name: "arm64 local"
      arch: arm64
      os: linux
      addons:
        apt:
          packages:
            - zlib1g-dev
            - libhdf5-dev
      script: autoreconf &&./scripts/install-hts.sh && ./configure  && make && make test
    - name: "arm64 local hdf5"
      arch: arm64
      os: linux
      addons:
        apt:
          packages:
            - zlib1g-dev
      script: autoreconf && ./scripts/install-hdf5.sh 2> /dev/null &&./scripts/install-hts.sh && ./configure --enable-localhdf5 && make && make test
    # - stage: deploy
    #   name: "GitHub Release"
    #   os: linux
    #   dist: trusty
    #   before_script:
    #     - wget http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1404/x86_64/cuda-repo-ubuntu1404_7.0-28_amd64.deb
    #     - sudo dpkg -i cuda-repo-ubuntu1404_7.0-28_amd64.deb
    #     - sudo apt-get update -qq
    #     - sudo apt-get install -y cuda-drivers cuda-core-6-5 cuda-cudart-dev-6-5
    #     - sudo apt-get clean
    #     - sudo ln -s /usr/local/cuda-6.5/ ${CUDA_HOME}
    #   script:
    #     - make dist
    #     - mkdir -p f5c-${TRAVIS_TAG}
    #     - make cuda=1 && mv f5c f5c-${TRAVIS_TAG}/f5c_x86_64_linux_cuda && make clean
    #     - make && mv f5c f5c-${TRAVIS_TAG}/f5c_x86_64_linux
    #     - cp -r README.md LICENSE docs f5c-${TRAVIS_TAG}/
    #     - mkdir -p f5c-${TRAVIS_TAG}/scripts
    #     - cp scripts/common.sh scripts/test.awk scripts/test.sh f5c-${TRAVIS_TAG}/scripts
    #     - tar -zcf f5c-${TRAVIS_TAG}-binaries.tar.gz f5c-${TRAVIS_TAG}
    #     - rm -rf f5c-${TRAVIS_TAG}
    #   deploy:
    #     provider: releases
    #     api_key:
    #       secure: GxxykACnOG9AFT2jnYGVtIKnteIojPjD5xtQlK49GVrmnM9ymXLaAtWhg1+IfxV2EKoDiuElNq+4RijNJubpzKnauyi6xdaHZN8Q2FwL4sqWqU0Xv953wYhCOgyzdJ0aHPeG8eK+PhsFetTekfdGz28yEakPPNSb+fPxawvIG+noEAenXMxOEddX8nybeU6C7FQxij3YDtztxNJN99lwZyYM72Polylh+K6H2JFCvH8JFhi/EYJSW8MtL/R2axE7q9n8T19n1OCufjh7t5vVzdFGmPtpq3HsBsyGXIjcBGqygO2DieA3zLp6tlxApDNbv6oFPZ8eNjir1XE5eex8RspIWWHW/RTRqAuU2W2mkL9HTVWGpafnBNwCL7LaxEIigRQXavfeucFRJSAyZ42EyzDaZxeYMGO7uIgLFzmxNXSKYbWEgvFo/7f2y6FlFQhpsf88fiaFDexW/A4dCaSG6EoMel5B95uV68/VqPk1jOBMi8h1NsaV74vTn3ttThAHGzhPYNUGfHCpNmI7v9mhpaQx1s25gEYIVFRJIBPM7Qa5Pmk29Wx+4PA2eAePh5LsNUjHjA7HscAFzDa4WyTLt7e6FG0nMSOiHSF32N4zxzlTUsIZ9RFx2MB/rVYIc9e5Cj4wsvnMtJm93G0KfVDKiU2b9K+7lzuURmdTGWYMb9k=
    #     file_glob: true
    #     file: f5c-*.tar.gz
    #     skip_cleanup: true
    #     on:
    #       branch: master
    #       repo: hasindu2008/f5c
    #       tags: true
    #   before_deploy:
    #     - make clean
